[.text-justify]
= Telegram Bots Long Polling - OSGi Bundle
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font
// Docinfo is used for foldable TOC.
// -> For full usage example see https://github.com/remkop/picocli
:docinfo: shared,private
:linkcss:
:stylesdir: https://www.ciechanowiec.eu/linux_mantra/
:stylesheet: adoc-css-style.css

This repository delivers a shaded OSGi bundle of https://github.com/rubenlagus/TelegramBots/tree/master/telegrambots-longpolling[_Telegram Bots Long Polling_].

== Features
. Maven coordinates for the bundle delivered by this repository:
+
[source, xml]
----
<dependency>
    <groupId>eu.ciechanowiec</groupId>
    <artifactId>org.telegram_telegrambots-longpolling</artifactId>
    <version>7.4.2</version>
</dependency>
----
. Maven coordinates for the original _Telegram Bots Long Polling_:
+
[source, xml]
----
<dependency>
    <groupId>org.telegram</groupId>
    <artifactId>telegrambots-longpolling</artifactId>
    <version>7.4.2</version>
</dependency>
----

. The bundle delivered by this repository includes a JAR file with all source code and original Javadocs, making its usage more convenient.

. To run the bundle delivered by this repository, Java 17 or higher is required.

. All dependencies not typically present in a standard OSGi environment and required by the bundle delivered by this repository are embedded within the bundle itself, ensuring it is self-sufficient and ready to run in an OSGi environment.

== License
The program is subject to MIT No Attribution License

Copyright © 2024 Herman Ciechanowiec

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

The Software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.
